[0m18:51:47.240980 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8ea8ec610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8e99ece20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8ea678730>]}


============================== 18:51:47.247029 | 9d42da62-4fe7-4801-b82a-c9720a86b9d8 ==============================
[0m18:51:47.247029 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:51:47.248613 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/cloudshell-user/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init dbt_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:51:47.265361 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/cloudshell-user/.dbt')}
[0m18:51:47.266709 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:51:47.269743 [debug] [MainThread]: Starter project path: /home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/include/starter_project
[0m18:51:47.274050 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:51:47.274833 [info ] [MainThread]: Setting up your profile.
[0m19:08:32.069133 [error] [MainThread]: Encountered an error:

[0m19:08:32.072179 [error] [MainThread]: Traceback (most recent call last):
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/cloudshell-user/.local/lib/python3.9/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m19:08:32.076529 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 1004.9919, "process_in_blocks": "168", "process_kernel_time": 0.125565, "process_mem_max_rss": "91988", "process_out_blocks": "72", "process_user_time": 1.749189}
[0m19:08:32.077559 [debug] [MainThread]: Command `dbt init` failed at 19:08:32.077388 after 1004.99 seconds
[0m19:08:32.078082 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8ea8ec610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8e99ec670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb8e99ec1c0>]}
[0m19:08:32.078685 [debug] [MainThread]: Flushing usage events
[0m19:08:32.092907 [debug] [MainThread]: An error was encountered while trying to flush usage events
